### ISSUE TITLE
__CollageImageUVsClass width and height arguments follow-through to right and bottom UV values.

### ISSUE THREAD

**Issue by hagand3** [tabularelf/Collage#16]
The arguments are inconsistent between what's being called and what's being processed. _uvX and _uvY are correct, but _uvW and _uvH point to _right and _bottomt inside method.

`var _uvs = new __CollageImageUVsClass(_texPage, owner.__texPageCount, _uvX, _uvY, _uvW, _uvH, _drawX, _drawY, _ogW, _ogH, _xOffset, _yOffset);`

This seems to have fixed it:
`function __CollageImageUVsClass(_texPageStruct, _texPageNum, _left, _top, _width, _height, _trimLeft = 0, _trimTop = 0, _ogW = 0, _ogH = 0, /*_cropRotate = 0,*/ _xOffset = 0, _yOffset = 0) constructor {
	left = _left;
	right = _left + _width;
	top = _top;
	bottom = _top + _height;
	trimLeft = _trimLeft;
	trimTop = _trimTop;
	//trimRight = _trimRight;
	//trimBottom = _trimBottom;
	//rotate = _cropRotate;
	normLeft = (_left / _texPageStruct.__width);
	normRight = ((_left + _width) / _texPageStruct.__width);
	normTop = (_top / _texPageStruct.__height);
	normBottom = ((_top + _height) / _texPageStruct.__height);
	normWidth = normLeft+normRight;
	normHeight = normTop+normBottom;
	originalWidth = _ogW;
	originalHeight = _ogH;
	xPos = _xOffset-_trimLeft;
	yPos = _yOffset-_trimTop;
	texturePageNum = _texPageNum;
	texturePageStruct = _texPageStruct;
}`

**Comment by tabularelf** [comment]
Fixed! https://github.com/tabularelf/Collage/releases/tag/v0.3.1
