### ISSUE TITLE
Loading Images from Web Server und use it in Collage()

### ISSUE THREAD

**Issue by Dirusym-bit** [tabularelf/Collage#28]
Hello, I have the following questions: I want to get my sprites from my own Web Server and insert them into a collage (Android only allows 30 texture pages). How exactly do I get them into the collage and then draw them? My problem was that I loaded the sprites individually with sprite add() and this always resulted in texture pages being created.

**Comment by tabularelf** [comment]
Howdy! That's interesting, I haven't really ran into a scenario where Android had a 30 texture page limit. At least on my own Android devices, I was able to exceed beyond that. The only limiting factors I've ever ran into was texture size limits. Perhaps hardware specific issue?

In any case, Collage works by batching images together as much as it can. Collage can take your sprites and put each one onto a single texture page, together. (It uses surfaces + a buffer backup to allow on the fly editing and updating)

```gml
// Creating a Collage group instance
texPage = new Collage("Characters", 1024, 1024, false, 0, true);

// Adding sprites into Collage
texPage.AddSprite(chr_bob_from_web, "spr_bob", true);

// Fetching information about the image
spr_bob = texPage.ImageGetInfo("spr_bob");

// Drawing
// draw_image is what I'd recommend for sprite index and collage image compatibility
draw_image(spr_bob, 0, x, y);
```

Collage does have an advanced batch mode, but if you're running into issues with `sprite_add` creating additional texture pages, then I'd suggest just forgoing the batch mode and sticking to adding sprites directly. Collage, as per the documentation https://docs.tabularelf.com/Collage/#/0.4.0/collage?id=addspritespriteid-identifier-iscopy-xorigin-yorigin-is3d, is able to clean up any sprites for you. (And it'll add them onto its surface + buffer combo, immediately)

**Comment by Dirusym-bit** [comment]
Thanks for you answer ! I just figure it out, it was because i make a loop and the system was too fast with the http request but was not ready because it get the Data the same time. I Just needed to add a extra Buffer and it works now fine :) !
